config/routes.rb
Rails.application.routes.draw do
  root 'profile#show'
  get '/profile' => 'profile#show', as: :profile_path

  resources :users, only: %i(update)
  resources :auction_items, only: %i(index show) do
    member do
      post :bid
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction_item.rb
class AuctionItem < ApplicationRecord
  include HasCurrency

  has_many :bids, dependent: :destroy
end

app/models/bid.rb
class Bid < ApplicationRecord
  include HasCurrency

  belongs_to :user
  belongs_to :auction_item

  scope :with_user, -> { includes(:user) }
  scope :by_date, -> { order(created_at: :desc) }
end

app/models/concerns/has_currency.rb
# A concern that adds a currency enumeration to a model.
# The model is expected to have a currency attribute/column.
module HasCurrency
  extend Enumerize

  enumerize :currency, in: { eur: 0, gbp: 1, usd: 2, sek: 3 }
end

app/models/exchange_rate_api_service.rb
require 'net/http'

# A wrapper class for the free currency conversion api.
# API key is stored in the credentials file.
class ExchangeRateApiService
  ENDPOINT = 'https://free.currconv.com/api/v7/convert'

  def exchange_rate(key)
    params = {
      q: key,
      compact: 'ultra',
      apiKey: Rails.application.credentials.currency_api_key
    }

    uri = URI.parse(ENDPOINT)
    uri.query = URI.encode_www_form(params)

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    response = http.request(Net::HTTP::Get.new(uri.request_uri))

    body = JSON.parse(response.body)

    body
  end
end

app/models/exchange_rate_storage.rb
# A class for loading exchange rates via api service to and from a base currency.
# The class is initialized with the base currency and
# provides two methods - from and to.
class ExchangeRateStorage
  attr_accessor :currency, :exchange_rates, :api_service

  def initialize(currency)
    self.currency = currency # the base currency
    self.exchange_rates = {} # a hash for caching the rates
    self.api_service = ExchangeRateApiService.new
  end

  # Gets an exchange rate for converting from
  # the specified currency to the base currency.
  def from(cur)
    return 1 if cur == currency

    key = "#{cur.upcase}_#{currency.upcase}"

    if exchange_rates[key].nil?
      exchange_rates.merge!(api_service.exchange_rate(key))
    end

    exchange_rates[key]
  end

  # Gets an exchange rate for converting to the specified currency
  # from the base currency.
  def to(cur)
    return 1 if cur == currency

    key = "#{currency.upcase}_#{cur.upcase}"

    if exchange_rates[key].nil?
      exchange_rates.merge!(api_service.exchange_rate(key))
    end

    exchange_rates[key]
  end
end

app/models/user.rb
class User < ApplicationRecord
  include HasCurrency

  has_many :bids, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :init

  def init
    @current_user = User.first
    @exchange_rate_storage = ExchangeRateStorage.new(@current_user.currency)
  end
end

app/controllers/auction_items_controller.rb
class AuctionItemsController < ApplicationController
  before_action :set_item, only: %i(show bid)

  def index
    @items = AuctionItem.all
  end

  def show
    @bid = Bid.new
  end

  def bid
    rate = @exchange_rate_storage.to(@item.currency)

    @item.bids.create!(currency: @item.currency,
                       price: bid_params[:price].to_f * rate,
                       user: @current_user)

    redirect_to auction_item_path(@item)
  end

  private

  def set_item
    @item = AuctionItem.find(params[:id])
  end

  def bid_params
    params.fetch(:bid, {}).permit(:price)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    user = User.first
    user.update(user_params)
    redirect_to :profile_path
  end

  def user_params
    params.fetch(:user, {}).permit(:name, :email, :currency)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def convert_bid_price(bid)
    rate = @exchange_rate_storage.from(bid.currency)
    (rate * bid.price).round(2)
  end

  def display_bid_price(bid)
    "#{convert_bid_price(bid)} #{@current_user.currency.text}"
  end
end

app/views/auction_items/index.html.erb
<h1>Auction Items</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Last bid</th>
      <th scope="col">Bids count</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <% bids_count = item.bids.size %>
        <td><%= link_to item.name, auction_item_path(item.id) %></td>
        <td><%= bids_count > 0 ? display_bid_price(item.bids.by_date.first) : 'No bids' %></td>
        <td><%= bids_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/auction_items/show.html.erb
<h1><%= @item.name %></h1>
<p><%= @item.description %></p>
<br />
<br />
<h2>Make a bid</h2>
<%= simple_form_for @bid, url: bid_auction_item_path(@item) do |f| %>
  <%= f.input :price, label: false %>
  <%= f.button :submit, class: 'btn-primary' %>
<% end %>
<br />
<br />
<h2>Bids</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">User</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
    <% @item.bids.with_user.by_date.each do |bid| %>
      <tr>
        <td><%= bid.user.name %></td>
        <td><%= display_bid_price(bid) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuctionTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="<%= root_path %>">AUCTION TASK</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= root_path %>">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= auction_items_path %>">Auction items</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>